### ISSUE TITLE
Cannot build Fiori Launchpad for XSA

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/devops-docker-mta-archive-builder#22]
Hi guys,

A very strange issue is detected.

So what I did I created a simple project to build Fiori launchpad.

When I run mtaBuild it fails with an error:  
```
npm ERR! 404 Not Found: sap-site-content-deployer@^1.6.4
```

While the real module name is @sap/site-content-deployer

I understand this project is only about docker image - but do you know probably where to go?

Also interesting observation - when building from web IDE same file - the build is performed correctly and the proper module name is put into archive

**Comment by ThePlenkov** [comment]
I have reproduced the case:
https://gitlab.com/theplenkov/xsa-flp-build/-/jobs/299487913
https://theplenkov.gitlab.io/-/xsa-flp-build/-/jobs/299487913/artifacts/flp-Content/package.json

**Comment by ThePlenkov** [comment]
Solved build by publishing sap-site-content-deployer 🤣 meanwhile it still fails during deploy - but currently it looks like my module controls building sites which use your docker image

**Comment by fwilhe** [comment]
The build tool used in this image is deprecated. Please move to [Cloud MTA Build Tool (MBT)](https://sap.github.io/cloud-mta-build-tool/) and [its docker image](https://hub.docker.com/r/devxci/mbtci) respectively.
