### ISSUE TITLE
npm ERR! code CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by mrgongora** [SAP/devops-docker-mta-archive-builder#31]
Hi,

The "CERT_HAS_EXPIRED" error happens when compiling a program from a pipeline in GIT. Does anyone know why this is happening?

![image](https://user-images.githubusercontent.com/82530323/114745171-69868200-9d1c-11eb-9664-b53624f59bea.png)

Greetings and thanks.

**Comment by radsoulbeard** [comment]
I recommend to use the new mbt tool https://hub.docker.com/r/devxci/mbtci
documentation: https://sap.github.io/cloud-mta-build-tool/
The MTA builder is deprecated and the image will also be deprecated.
