### ISSUE TITLE
mta image only usable when a volume is mounted

### ISSUE THREAD

**Issue by marcusholl** [SAP/devops-docker-mta-archive-builder#5]
In case we issue a simple 

`docker run  -it --rm ppiper/mta-archive-builder mtaBuild –version`

with out mounting a volume so that the workdir is provided from outside alongside with the proper permissions the build command (... a simple version command) fails with

`ERROR: failed to clear directory .mta`

I guess it should be possible to use the mta-archive-builder also with nothing mounted into it.

**Comment by fwilhe** [comment]
Closing as the image is not maintained anymore.
