### ISSUE TITLE
Docker Image MTA+Browsers for PR-Voting

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/devops-docker-mta-archive-builder#6]
Hi everyone!

In my project, we manually run Unit Tests for an MTA project including Java Services (`mvn verify`), Node.js modules (`npm run test`) and Fiori-Apps (`@sap/grunt-sapui5-bestpractice-test`). We use a Piper Template and configure the docker image for running the tests:

```yaml
  'Pull-Request Voting':
    dockerCommand: tools/run_tests.sh
    dockerImage: xxx
```

Unfortunately, there currently is no officially supported docker image containing everything: The MTA-Build-Tooling (for us mvn and node would be enough) _and_ the Webbrowsers (`@sap/grunt-sapui5-bestpractice-test` relies on Chrome Headless (Chromium does fine as well)). There are only the two distinct images `ppiper/mta-archive-builder` and `ppiper/node-browsers`.

Would it be possible to add Chromium to the MTA-Build-Tooling-Image? Or maybe add another image building on `ppiper/mta-archive-builder` that just adds the few lines of code in `ppiper/node-browsers`?

Adding it to the MTA-Builder-Image seems like the most reasonable thing to me: MTAs will include Fiori-UIs in most cases. These must use `@sap/grunt-sapui5-bestpractice-build` to use the new portal service on SCP. The recommended way to test them is the `@sap/grunt-sapui5-bestpractice-test`, that is (to my knowledge) the approach suggested by WebIDE to be used. So having support for it in the default image seems logical.

Thank you very much for considering!
Kind regards
Lukas

**Comment by DerGuteWolf** [comment]
Isn't the most current idea instead of the bestpractice-build/bestpractice-test to use the new UI5 tooling (cf. https://github.com/SAP/ui5-tooling and https://help.sap.com/viewer/825270ffffe74d9f988a0f0066ad59f0/CF/en-US/a3d3182aa1044cf3a0aa577158a977d6.html )?
See https://github.com/SAP/openui5-sample-app/#openui5-sample-app : npm test should run ESLint and the Karma Test runner with the UI5 Plugin.
So how could this best be integrated here?

**Comment by fwilhe** [comment]
The build tool used in this image is deprecated. Please move to [Cloud MTA Build Tool (MBT)](https://sap.github.io/cloud-mta-build-tool/) and [its docker image](https://hub.docker.com/r/devxci/mbtci) respectively.
